### ISSUE TITLE
boost::string_ref / std::string_view?

### ISSUE THREAD

**Issue by pravic** [ned14/quickcpplib#1]
It would be nice to have them as well.

**Comment by ned14** [comment]
Apart from VS2015, any of the compilers which boost-lite works on provide `<experimental/string_view>` already. I'll be dropping support for VS2015 soon enough, so I'd say this issue will get closed then.

**Comment by ned14** [comment]
Sorry, I forgot to mention that I added this to https://github.com/ned14/quickcpplib/blob/master/include/string_view.hpp a while back. Apologies.

**Comment by pravic** [comment]
Okay, it is even better then :)
