### ISSUE TITLE
`packed_backtrace.hpp` missing includes with `QUICKCPPLIB_USE_STD_SPAN`

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/quickcpplib#18]
https://github.com/ned14/quickcpplib/blob/a47807c6b8ed0a4f2de7ffd8315a431de6d4278d/include/quickcpplib/packed_backtrace.hpp#L26-L35

However, the file contains
https://github.com/ned14/quickcpplib/blob/a47807c6b8ed0a4f2de7ffd8315a431de6d4278d/include/quickcpplib/packed_backtrace.hpp#L317
and
https://github.com/ned14/quickcpplib/blob/a47807c6b8ed0a4f2de7ffd8315a431de6d4278d/include/quickcpplib/packed_backtrace.hpp#L405
which relies on `<cstdlib>` and `<stdexcept>` being included by `"span.hpp"`. This is the case for gsl / span-lite, but both gcc and msvc standard library implementations of `span` include neither of them. Therefore `QUICKCPPLIB_USE_STD_SPAN` is currently somewhat broken.

**Comment by ned14** [comment]
Many thanks for the bug report!

**Comment by BurningEnlightenment** [comment]
@ned14 thanks for fixing this promptly!

Just a heads up: The IntelliSense/EDG version included in the upcoming VS 16.8 release ICEs _somewhere_ in outcome's `basic_result.hpp`, i.e. IntelliSense will be disabled for everything (transitively) including `basic_result.hpp`.

**Comment by ned14** [comment]
Well that sucks. I'm not onto 16.8, but when it releases I'll go prod Microsoft if it's still there. You may not be aware that Outcome trunk is within VS's test suite, so they tend to notice quickly when Outcome blows their stuff up.
