### ISSUE TITLE
cmake property `CXX_STATIC_RUNTIME` ignores `CMAKE_MSVC_RUNTIME_LIBRARY`

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/quickcpplib#21]
It would be nice if `QuickCppLibSetupProject` would respect [`CMAKE_MSVC_RUNTIME_LIBRARY`](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html) if defined, because otherwise it is impossible to build the statically linked runtime variant with the current vcpkg port. E.g. changing the following line
https://github.com/ned14/quickcpplib/blob/9a16849c29b9a272c6aaabbd610007e470063352/cmakelib/QuickCppLibSetupProject.cmake#L66
to something like
```cmake
if (NOT DEFINED CMAKE_MSVC_RUNTIME_LIBRARY OR CMAKE_MSVC_RUNTIME_LIBRARY MATCHES "^MultiThreaded.*DLL$")
  set_property(GLOBAL PROPERTY CXX_STATIC_RUNTIME OFF)
else()
  set_property(GLOBAL PROPERTY CXX_STATIC_RUNTIME ON)
endif()
```
would work in a backward compatible manner.

**Comment by ned14** [comment]
Oh dear, I also missed this. Sorry. Yes this patchset would be fine, if you raise a PR I will merge it.
