### ISSUE TITLE
Missing <cstring> include when building with vcpkg

### ISSUE THREAD

**Issue by oracle-9** [ned14/quickcpplib#26]
I wasn't sure if I should report this here or on the outcome repo.
Anyway, building outcome 2.2.2-20211208 (the latest version available in vcpkg) produces the following compiler error:
```
include/quickcpplib/boost/test/unit_test.hpp:188:12: error: ‘strstr’ was not declared in this scope
  188 |         if(strstr(argv[n] + 2, "help"))
      |            ^~~~~~

include/quickcpplib/boost/test/unit_test.hpp:94:1: note: ‘strstr’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
   93 | #include "../../console_colours.hpp"
  +++ |+#include <cstring>
   94 | //#ifdef _WIN32
```
which is here: https://github.com/ned14/quickcpplib/blob/d2aa76116bff915ff1980c071b3e154295d0c0c7/include/quickcpplib/boost/test/unit_test.hpp#L189

(The list of include errors goes on.)

In b4b23064d1e8468b718efc2c8287b94a55035d10 this is fixed.
However, the errors still occur when building the latest version of outcome with vcpkg.
Is there any easy fix to this?

**Comment by BurningEnlightenment** [comment]
> Is there any easy fix to this?

Sadly no, you will either need to wait until the vcpkg team merges the port update or copy the updated port to a private/custom vcpkg-registry (assuming you use manifest mode).
