### ISSUE TITLE
Option to disable gsl-lite if GSL proper is already included ?

### ISSUE THREAD

**Issue by jcelerier** [ned14/quickcpplib#28]
Hi,

I have some code that uses gsl's version of span. Sadly this causes ugly compile errors with this because of gsl-lite: 

```
/__w/score/score/src/lib/score/actions/ActionManager.cpp:63:9: note: add explicit 'this' or '*this' capture
In file included from /__w/score/score/3rdparty/quickcpplib/include/quickcpplib/span.hpp:68,
                 from /__w/score/score/3rdparty/quickcpplib/include/quickcpplib/packed_backtrace.hpp:29,
                 from /__w/score/score/3rdparty/quickcpplib/include/quickcpplib/ringbuffer_log.hpp:47,
                 from /__w/score/score/3rdparty/llfio/include/llfio/v2.0/config.hpp:216,
                 from /__w/score/score/3rdparty/llfio/include/llfio/v2.0/llfio.hpp:58,
                 from /__w/score/score/3rdparty/llfio/include/llfio/llfio.hpp:18,
                 from /__w/score/score/3rdparty/llfio/include/llfio.hpp:1,
/__w/score/score/3rdparty/quickcpplib/include/quickcpplib/gsl-lite/include/gsl/gsl-lite.hpp: At global scope:
/__w/score/score/3rdparty/quickcpplib/include/quickcpplib/gsl-lite/include/gsl/gsl-lite.hpp:1128:7: error: redeclared with 1 template parameter
 1128 | class span;
      |       ^~~~
In file included from /__w/score/score/3rdparty/libossia/3rdparty/GSL/include/gsl/span:22,
/__w/score/score/3rdparty/libossia/3rdparty/GSL/include/gsl/span_ext:47:7: note: previous declaration 'template<class ElementType, long unsigned int Extent> class gsl::span' used 2 template parameters
   47 | class span;
      |       ^~~~
```

Would you be open to a PR that adds detection of GSL (maybe through a simple QUICKCPPLIB_GSL_AVAILABLE define or something similar?)

... although gsl::span does not seem to fit the bill.. I hit this with gsl/span:

```
#if !defined(_MSC_VER) || _MSC_VER < 1926
  static_assert(std::is_standard_layout<buffers_type>::value, "buffers_type is not a standard layout type!");
#endif
```

in

```
/home/jcelerier/ossia/score/3rdparty/llfio/include/llfio/v2.0/byte_io_multiplexer.hpp:389: erreur : static_assert failed due to requirement 'std::is_standard_layout<gsl::span<llfio_v2_613d8707::byte_io_multiplexer::buffer_type, 18446744073709551615>>::value' "buffers_type is not a standard layout type!"
In file included from /home/jcelerier/ossia/score/src/lib/score/tools/RecursiveWatch.cpp:27:
In file included from /home/jcelerier/ossia/score/3rdparty/llfio/include/llfio.hpp:1:
In file included from /home/jcelerier/ossia/score/3rdparty/llfio/include/llfio/llfio.hpp:18:
In file included from /home/jcelerier/ossia/score/3rdparty/llfio/include/llfio/v2.0/llfio.hpp:67:
In file included from /home/jcelerier/ossia/score/3rdparty/llfio/include/llfio/v2.0/detail/impl/../../dynamic_thread_pool_group.hpp:526:
In file included from /home/jcelerier/ossia/score/3rdparty/llfio/include/llfio/v2.0/detail/impl/dynamic_thread_pool_group.ipp:27:
In file included from /home/jcelerier/ossia/score/3rdparty/llfio/include/llfio/v2.0/detail/impl/../../file_handle.hpp:28:
In file included from /home/jcelerier/ossia/score/3rdparty/llfio/include/llfio/v2.0/lockable_byte_io_handle.hpp:28:
In file included from /home/jcelerier/ossia/score/3rdparty/llfio/include/llfio/v2.0/byte_io_handle.hpp:28:
/home/jcelerier/ossia/score/3rdparty/llfio/include/llfio/v2.0/byte_io_multiplexer.hpp:389:3: error: static_assert failed due to requirement 'std::is_standard_layout<gsl::span<llfio_v2_613d8707::byte_io_multiplexer::buffer_type, 18446744073709551615>>::value' "buffers_type is not a standard layout type!"
  static_assert(std::is_standard_layout<buffers_type>::value, "buffers_type is not a standard layout type!");
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by BurningEnlightenment** [comment]
IIRC the standard layout guarantees are required for interconvertibility with `struct iovec` and the like. And as long as gsl doesn't conform to its memory layout its unusable with this library (at the very least on POSIX).

However, the currently referenced gsl-lite commit doesn't seem to conform to the `(data, size)` layout either: 
https://github.com/gsl-lite/gsl-lite/blob/f7d45ab65f42360817d0e338e78d6f4241868d98/include/gsl/gsl-lite.hpp#L3925-L3927

Maybe we could switch the span polyfill over to [span-lite] which seems to tick all the boxes and shouldn't be incompatible with any other library.

[span-lite]: https://github.com/martinmoene/span-lite

**Comment by ned14** [comment]
Don't we already polyfill to `std::span` when available? If so I don't see necessarily the issue with letting a user inject their own implementation.

Did I replace LLFIO's `buffer_type` with a local `span` implementation in order to ensure `struct iovec` layout compatibility? I can't remember. In any case, it seems to me that LLFIO probably needs to do its own thing going forth.

**Comment by BurningEnlightenment** [comment]
`buffer_type` is a custom (albeit incomplete) local span implementation, `buffers_type` isn't.

> If so I don't see necessarily the issue with letting a user inject their own implementation.

I don't think we should allow arbitrary user provided implementations, because that might cause ODR violations, include order issues and the like. However, I think we should replace our polyfill. `gsl-lite` is incompatible with `gsl` proper while `span-lite` doesn't suffer these issues. In addition to that `span-lite` is more lightweight and also shares the author/maintainer with `gsl-lite`.

**Comment by ned14** [comment]
Is this issue closed?
