### ISSUE TITLE
bitwise trie segmentation fault

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/quickcpplib#31]
The CI pipeline segfaulted during the bitwise trie test and AFAICT none of the recent changes should influence that test in particular. So it is likely an older bug.

https://github.com/ned14/quickcpplib/runs/7180783421?check_suite_focus=true#step:3:33

**Comment by ned14** [comment]
You're right it's longstanding.

I cannot repeat it with clang on any hardware I own. It seems to appear exclusively on CI. I've stuck it into 24 hour loops on local hardware, not a single repro.

I keep meaning to dig a bit deeper, but it's that free time thing as usual.

**Comment by BurningEnlightenment** [comment]
No worries, I only opened this in order to document that there is a bug. This helps me not freaking out in case of future CI failure 😅

**Comment by ned14** [comment]
Ah, I fixed this some months ago. Turns out it was a failure to initialise a member variable in the structures in the test code, and for some reason that caused clang to do bad codegen which was rather alarming. Anyway, fixed!
