### ISSUE TITLE
Installs cmake files into a non-standard location /usr/local/share/cmakelib/Q

### ISSUE THREAD

**Issue by yurivict** [ned14/quickcpplib#44]
cmake doesn't look there.

**Comment by BurningEnlightenment** [comment]
It's the job of [QuickCppLibBootstrap.cmake](https://github.com/ned14/quickcpplib/blob/master/cmake/QuickCppLibBootstrap.cmake) to find and add that path to the `CMAKE_MODULE_PATH`. The bootstrap script must be copied/included with the downstream dependent.

**Comment by yurivict** [comment]
Ok, I agree, thanks!
