### ISSUE TITLE
[feature-request] Please, consider a more portable include-header pattern for nonstd-xxx libs

### ISSUE THREAD

**Issue by ngrodzitski** [ned14/quickcpplib#48]
I want to make a Conan package for this library (for CCI conan-center-index).
And I have an issue with that kind of including nonstd family of libs
https://github.com/ned14/quickcpplib/blob/9aaddae850e2c6dd8a66a9833d1172d1515e9dbf/include/quickcpplib/byte.hpp#L57

These libs exist in CCI, but the include for them would look like this:
```c++
#include "nonstd/byte.hpp" 
 // or 
#include <nonstd/byte.hpp> 
```

It would be great if you either help with it yourself or willing to consider a PR with relevant changes.

**Comment by BurningEnlightenment** [comment]
I think it'd be acceptable to follow a pattern similar to the `status-code` inclusion in `outcome` (see [here](https://github.com/ned14/outcome/blob/1407d02d60c604e642ae202dbbd721e8c9851fbb/include/outcome/experimental/status_result.hpp#L37-L43)). However, note that this case differs a bit as `byte-lite` isn't built and therefore not dragged in via `find_package` (I believe Niall would like to preserve this behavior for the vendored case).

Alternatively, you could simply require at least C++17 (`-DQUICKCPPLIB_REQUIRE_CXX17=ON`) and skip the `byte-lite` dependency altogether.

And by the way there have been bugs with certain `gsl-lite`/`span-lite`/`byte-lite` versions, so please make sure to use those currently referenced and/or include a warning similar to the one displayed by `vcpkg`:
> QuickCppLib and its downstream dependencies Outcome and LLFIO were tested against span-lite version 0.10.3 and byte-lite version 0.3.0. They are not guaranteed to work with newer versions, with failures experienced in the past up-to-and-including runtime crashes. You can pin the versions as verified to work in QuickCppLib's CI in your manifest file by adding:

Lastly, thanks for bringing these libraries to conan 🎉

**Comment by ngrodzitski** [comment]
> Alternatively, you could simply require at least C++17

That was my initial plan (even C++20). My final goal is to make LLFIO package. And I wanted to cut support to C++20, but then it appeared that `outcome` is already in CCI. It is a single header version (not quite what required for LLFIO), that's fine I can update it so it would be possible use true version (e.g. using conan-package-options), but already existing package specifies it works from C++14 (https://github.com/conan-io/conan-center-index/blob/master/recipes/outcome/all/conanfile.py#L25) so I'd prefer to keep it that way (to argue in PR  that now `outcome` "needs" that breaking change is likely to be hard). So need to go through C++14.

Thanks for the link with an example, I'll try to make PR in a similar fashion.

**Comment by ngrodzitski** [comment]
@BurningEnlightenment 
Would it be possible to switch to https://github.com/martinmoene/optional-lite (exists in conan) instead of https://github.com/akrzemi1/Optional (doesn't exist)?

**Comment by ngrodzitski** [comment]
Such approach is discouraged in Conan: https://github.com/conan-io/conan-center-index/pull/15995#issuecomment-1470227679 
And adding yet another "optional" package in 2023 looks odd. And with regard to quickcpplib it already uses nonstd-xxx (aka xxx-lite) libraries.
So why not to do the same for optional...
