### ISSUE TITLE
No __int128 on 32 bit platforms

### ISSUE THREAD

**Issue by clausecker** [ned14/quickcpplib#50]
The `__int128` type is only supported on 64 bit platforms with gcc and clang.  To detect its availability correctly, use

    #if defined(__SIZEOF_INT128__)

instead of

    #if defined(__GNUC__) || defined(__clang__)

**Comment by ned14** [comment]
Thanks for the BR.

I'm seeing in the source code here:

```
#if(defined(__GNUC__) || defined(__clang__)) && __SIZEOF_INT128__ > 0
```

i.e. never are we not testing for `__SIZEOF_INT128__`. Can you say on which line did you find this?

**Comment by clausecker** [comment]
Hm looks like you may have already fixed that, but as you do not make releases, it is unknown how long it takes for these changes to percolate downstream.

**Comment by BurningEnlightenment** [comment]
Out of interest: Are you using a package manager? And if yes: Which one?

**Comment by clausecker** [comment]
I'm a maintainer of the FreeBSD ports collection where I noticed this problem in the version of quickcpplib we ship.

**Comment by ned14** [comment]
I'm going to assume this is fixed and close it. Thanks for the BR!
