### ISSUE TITLE
So what is actually _in_ this library?

### ISSUE THREAD

**Issue by eyalroz** [ned14/quickcpplib#8]
At the moment, neither README.md  nor the documentation (see issue #7) tell us what is actually _in_ this library. You're essentially telling us that ["oh yes, it's very nice"](https://youtu.be/GYcopzJ-T9w?t=45).

**Comment by ned14** [comment]
I've replaced that blurb with:

    Common library for most of https://github.com/ned14's open source libraries. Automates away
    hassle for build, sanitising, linting, documentation, super building, dependencies, modules, single
    include generation, and lack of later C++ facilities in C++ 14.

For this library, I'm minded not to document it further.
